{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Access denied for user 'root'@'localhost' (using password: NO)\u001b[39m","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:28:12.409"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Access denied for user 'root'@'localhost' (using password: NO)\u001b[39m","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:28:49.539"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Unknown database 'database_development'\u001b[39m","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'database_development'\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:34:59.719"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Unknown database 'database_development'\u001b[39m","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'database_development'\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:36:05.059"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Unknown database 'database_development'\u001b[39m","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'database_development'\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:36:18.541"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Unknown database 'database_development'\u001b[39m","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'database_development'\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:36:25.243"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Unknown database 'database_development'\u001b[39m","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'database_development'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'database_development'\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 03:36:37.466"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 03:48:47.177"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 03:49:33.781"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnable to connect to the database: Unknown database 'coach_ally'\u001b[39m","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'coach_ally'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'coach_ally'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'coach_ally'\n    at ConnectionManager.connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\node_modules\\sequelize\\lib\\sequelize.js:457:5)","timestamp":"2025-05-16 04:14:34.852"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:14:59.425"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:20:23.163"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:22:24.850"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:24:02.127"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:26:51.933"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:28:03.603"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:29:44.950"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:32:29.311"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:32:41.734"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:33:25.811"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:36:43.695"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:50:57.842"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:52:05.023"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 04:53:57.674"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 04:59:15.054"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:00:00.557"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:08:10.263"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:10:26.208"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:10:49.137"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:11:49.790"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:11:58.143"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:12:10.869"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:12:33.618"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:12:40.386"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:12:54.762"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:14:11.964"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:32:20.881"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:34:05.250"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:35:52.888"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:37:52.428"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUncaught Exception: listen EADDRINUSE: address already in use :::5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\Users\\leone\\OneDrive\\Desktop\\322_final\\backend\\server.js:136:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-05-16 05:37:58.574"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:40:32.279"}
{"level":"\u001b[31merror\u001b[39m","message":"\t\u001b[31mUnhandled error:\u001b[39m","timestamp":"2025-05-16 05:51:39.097"}
